package com.poly.model;

import com.formdev.flatlaf.intellijthemes.FlatArcIJTheme;
import com.poly.utils.MsgBox;
import com.poly.utils.XImage;
import javax.swing.ImageIcon;

/**
 *
 * @author admin
 */
public class DoiMatKhau extends javax.swing.JFrame {

    /**
     * Creates new form DoiMatKhau
     */
    public DoiMatKhau() {
        initComponents();
        this.setIconImage(XImage.getAppIcon());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblShowPass = new javax.swing.JLabel();
        pswMatKhauCu = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        lblShowPass1 = new javax.swing.JLabel();
        pswMatKhauMoi = new javax.swing.JPasswordField();
        lblShowPass2 = new javax.swing.JLabel();
        pswXacNhan = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        btnHuy = new javax.swing.JButton();
        btnDoiMatKhau = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("KLShop - Đổi mật khẩu");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("ĐỔI MẬT KHẨU");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 28, 197, 41));

        jLabel3.setText("Chú ý các trường (*) là bắt buộc.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 78, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("<html><p><strong style=\"color:red\">*</strong> Mật khẩu cũ:</p></htm>");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        lblShowPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShowPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/unhide.jpg"))); // NOI18N
        lblShowPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShowPassMouseClicked(evt);
            }
        });
        jPanel1.add(lblShowPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 40, 40));

        pswMatKhauCu.setText("123123");
        jPanel1.add(pswMatKhauCu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 570, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("<html><p><strong style=\"color:red\">*</strong> Mật khẩu mới:</p></htm>");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        lblShowPass1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShowPass1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/unhide.jpg"))); // NOI18N
        lblShowPass1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShowPass1MouseClicked(evt);
            }
        });
        jPanel1.add(lblShowPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 40, 40));

        pswMatKhauMoi.setText("123123");
        jPanel1.add(pswMatKhauMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 570, 40));

        lblShowPass2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShowPass2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/unhide.jpg"))); // NOI18N
        lblShowPass2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShowPass2MouseClicked(evt);
            }
        });
        jPanel1.add(lblShowPass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 40, 40));

        pswXacNhan.setText("123123");
        jPanel1.add(pswXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 570, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("<html><p><strong style=\"color:red\">*</strong> Xác nhận mật khẩu:</p></htm>");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        btnHuy.setText("Hủy ");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        jPanel1.add(btnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 210, 60));

        btnDoiMatKhau.setText("Xác nhận");
        jPanel1.add(btnDoiMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 210, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 531));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    boolean hide1 = true;
    private void lblShowPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShowPassMouseClicked
        if(hide1 ==true){
            pswMatKhauCu.setEchoChar((char) 0);
            lblShowPass.setIcon(new ImageIcon(DangNhap.class.getResource("/com/poly/icon/hide.jpg")));
            hide1=false;
        }else{
            pswMatKhauCu.setEchoChar('*');
            lblShowPass.setIcon(new ImageIcon(DangNhap.class.getResource("/com/poly/icon/unhide.jpg")));
            hide1=true;
        }
    }//GEN-LAST:event_lblShowPassMouseClicked
    boolean hide2 = true;
    private void lblShowPass1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShowPass1MouseClicked
       if(hide2 ==true){
            pswMatKhauMoi.setEchoChar((char) 0);
            lblShowPass1.setIcon(new ImageIcon(DangNhap.class.getResource("/com/poly/icon/hide.jpg")));
            hide2=false;
        }else{
            pswMatKhauMoi.setEchoChar('*');
            lblShowPass1.setIcon(new ImageIcon(DangNhap.class.getResource("/com/poly/icon/unhide.jpg")));
            hide2=true;
        }
    }//GEN-LAST:event_lblShowPass1MouseClicked
     boolean hide3 = true;
    private void lblShowPass2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShowPass2MouseClicked
       if(hide3 ==true){
            pswXacNhan.setEchoChar((char) 0);
            lblShowPass2.setIcon(new ImageIcon(DangNhap.class.getResource("/com/poly/icon/hide.jpg")));
            hide3=false;
        }else{
            pswXacNhan.setEchoChar('*');
            lblShowPass2.setIcon(new ImageIcon(DangNhap.class.getResource("/com/poly/icon/unhide.jpg")));
            hide3=true;
        }
    }//GEN-LAST:event_lblShowPass2MouseClicked

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
       if (MsgBox.confirm(this, "Bạn muốn kết thúc ứng dụng?")) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnHuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatArcIJTheme.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoiMatKhau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoiMatKhau;
    private javax.swing.JButton btnHuy;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblShowPass;
    private javax.swing.JLabel lblShowPass1;
    private javax.swing.JLabel lblShowPass2;
    private javax.swing.JPasswordField pswMatKhauCu;
    private javax.swing.JPasswordField pswMatKhauMoi;
    private javax.swing.JPasswordField pswXacNhan;
    // End of variables declaration//GEN-END:variables
}
