package com.poly.model;

import com.formdev.flatlaf.intellijthemes.FlatArcIJTheme;
import com.poly.utils.Auth;
import com.poly.utils.MsgBox;
import com.poly.utils.XImage;
import com.poly.utils.clock;

/**
 *
 * @author admin
 */
public class ManHinhChinh extends javax.swing.JFrame {

    /**
     * Creates new form ManHinhChinh
     */
    public ManHinhChinh() {
        initComponents();
        this.setIconImage(XImage.getAppIcon());
        dongHo();
    }
    public void dongHo(){
        clock dongho = new clock(lblDongHo);
        dongho.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblDongHo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnTaiKhoan = new javax.swing.JButton();
        btnNhanVien = new javax.swing.JButton();
        btnKhachHang = new javax.swing.JButton();
        btnLoaiSanPham = new javax.swing.JButton();
        btnSanPham = new javax.swing.JButton();
        btnKichThuoc = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();
        btnThanhToan = new javax.swing.JButton();
        btnHoaDon = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar3 = new javax.swing.JMenuBar();
        mnuHeThong_mniDMK2 = new javax.swing.JMenu();
        mni_DoiMK2 = new javax.swing.JMenuItem();
        mnuHeThong_mniDX = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuHeThong_mniKT = new javax.swing.JMenuItem();
        mnuTK = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KLShop - Màn hình chính");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/img/logo-klshop.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 790, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        lblDongHo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblDongHo.setForeground(new java.awt.Color(255, 255, 255));
        lblDongHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/clock.png"))); // NOI18N
        lblDongHo.setText("10:00 AM");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PHẦN MỀM QUẢN LÝ SHOP QUẦN ÁO ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 555, Short.MAX_VALUE)
                .addComponent(lblDongHo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblDongHo, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 1000, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnTaiKhoan.setBackground(new java.awt.Color(0, 153, 153));
        btnTaiKhoan.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        btnTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/nguoidung.png"))); // NOI18N
        btnTaiKhoan.setText("Tài khoản");
        btnTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaiKhoanActionPerformed(evt);
            }
        });

        btnNhanVien.setBackground(new java.awt.Color(0, 153, 153));
        btnNhanVien.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/nhanvien.png"))); // NOI18N
        btnNhanVien.setText("Nhân viên");
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });

        btnKhachHang.setBackground(new java.awt.Color(0, 153, 153));
        btnKhachHang.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        btnKhachHang.setText("Khách hàng");
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });

        btnLoaiSanPham.setBackground(new java.awt.Color(0, 153, 153));
        btnLoaiSanPham.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnLoaiSanPham.setForeground(new java.awt.Color(255, 255, 255));
        btnLoaiSanPham.setText("Loại sản phẩm");
        btnLoaiSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoaiSanPhamActionPerformed(evt);
            }
        });

        btnSanPham.setBackground(new java.awt.Color(0, 153, 153));
        btnSanPham.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnSanPham.setForeground(new java.awt.Color(255, 255, 255));
        btnSanPham.setText("Sản phẩm");
        btnSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanPhamActionPerformed(evt);
            }
        });

        btnKichThuoc.setBackground(new java.awt.Color(0, 153, 153));
        btnKichThuoc.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnKichThuoc.setForeground(new java.awt.Color(255, 255, 255));
        btnKichThuoc.setText("Kích thước");
        btnKichThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKichThuocActionPerformed(evt);
            }
        });

        btnDangXuat.setBackground(new java.awt.Color(51, 51, 51));
        btnDangXuat.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnDangXuat.setForeground(new java.awt.Color(255, 255, 255));
        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/dangxuat.png"))); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        btnThanhToan.setBackground(new java.awt.Color(0, 153, 153));
        btnThanhToan.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        btnThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/banhang.png"))); // NOI18N
        btnThanhToan.setText("Thanh toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        btnHoaDon.setBackground(new java.awt.Color(0, 153, 153));
        btnHoaDon.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        btnHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/hoadon.png"))); // NOI18N
        btnHoaDon.setText("Hóa đơn");
        btnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaDonActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(255, 0, 51));
        btnThoat.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/dangxuat.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnKichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnKichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/img/ao1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 790, 650));

        mnuHeThong_mniDMK2.setText("Hệ thống");
        mnuHeThong_mniDMK2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnuHeThong_mniDMK2.setMargin(new java.awt.Insets(0, 0, 0, 5));

        mni_DoiMK2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        mni_DoiMK2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mni_DoiMK2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/Refresh.png"))); // NOI18N
        mni_DoiMK2.setText("Đổi mật khẩu");
        mni_DoiMK2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_DoiMK2ActionPerformed(evt);
            }
        });
        mnuHeThong_mniDMK2.add(mni_DoiMK2);

        mnuHeThong_mniDX.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        mnuHeThong_mniDX.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnuHeThong_mniDX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/Log out.png"))); // NOI18N
        mnuHeThong_mniDX.setText("Đăng xuất");
        mnuHeThong_mniDX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHeThong_mniDXActionPerformed(evt);
            }
        });
        mnuHeThong_mniDMK2.add(mnuHeThong_mniDX);
        mnuHeThong_mniDMK2.add(jSeparator1);

        mnuHeThong_mniKT.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, java.awt.event.InputEvent.SHIFT_MASK));
        mnuHeThong_mniKT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnuHeThong_mniKT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/power.png"))); // NOI18N
        mnuHeThong_mniKT.setText("Kết thúc");
        mnuHeThong_mniKT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHeThong_mniKTActionPerformed(evt);
            }
        });
        mnuHeThong_mniDMK2.add(mnuHeThong_mniKT);

        jMenuBar3.add(mnuHeThong_mniDMK2);

        mnuTK.setText("Thống kê doanh thu");
        mnuTK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mnuTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuTKMouseClicked(evt);
            }
        });
        jMenuBar3.add(mnuTK);

        setJMenuBar(jMenuBar3);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mni_DoiMK2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_DoiMK2ActionPerformed
        new DoiMatKhau().setVisible(true);
    }//GEN-LAST:event_mni_DoiMK2ActionPerformed

    private void mnuHeThong_mniDXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHeThong_mniDXActionPerformed
        if (MsgBox.confirm(this, "Bạn muốn đăng xuất?")) {
            new DangNhap().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_mnuHeThong_mniDXActionPerformed

    private void mnuHeThong_mniKTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHeThong_mniKTActionPerformed
        if (MsgBox.confirm(this, "Bạn muốn kết thúc ứng dụng?")) {
            System.exit(0);
        }
    }//GEN-LAST:event_mnuHeThong_mniKTActionPerformed

    private void mnuTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuTKMouseClicked
          new ThongKeJFrame().setVisible(true);
//        if (!Auth.isManager()) {
//            MsgBox.alert(this, "Bạn không có quyền xem Doanh Thu này!");
//        } else {
//            new ThongKe().setVisible(true);
//        }
    }//GEN-LAST:event_mnuTKMouseClicked

    private void btnTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaiKhoanActionPerformed
        new TaiKhoanJFrame().setVisible(true);
    }//GEN-LAST:event_btnTaiKhoanActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
         new NhanVienJFrame().setVisible(true);
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        if (MsgBox.confirm(this, "Bạn muốn kết thúc ứng dụng?")) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
         new KhachHangJFrame().setVisible(true);
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void btnSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanPhamActionPerformed
        new SanPhamJFrame().setVisible(true);
    }//GEN-LAST:event_btnSanPhamActionPerformed

    private void btnLoaiSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoaiSanPhamActionPerformed
        new LoaiSPJFrame().setVisible(true);
    }//GEN-LAST:event_btnLoaiSanPhamActionPerformed

    private void btnKichThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKichThuocActionPerformed
        new KichThuocJFrame().setVisible(true);
    }//GEN-LAST:event_btnKichThuocActionPerformed

    private void btnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoaDonActionPerformed
         new HoaDonJFrame().setVisible(true);
    }//GEN-LAST:event_btnHoaDonActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
         new ThanhToan().setVisible(true);
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
       if (MsgBox.confirm(this, "Bạn muốn đăng xuất ứng dụng?")) {
           this.dispose();
           new DangNhap().setVisible(true);
        }
    }//GEN-LAST:event_btnDangXuatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
         FlatArcIJTheme.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManHinhChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnKichThuoc;
    private javax.swing.JButton btnLoaiSanPham;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnSanPham;
    private javax.swing.JButton btnTaiKhoan;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JMenuItem mni_DoiMK;
    private javax.swing.JMenuItem mni_DoiMK1;
    private javax.swing.JMenuItem mni_DoiMK2;
    private javax.swing.JMenu mnuHeThong_mniDMK;
    private javax.swing.JMenu mnuHeThong_mniDMK1;
    private javax.swing.JMenu mnuHeThong_mniDMK2;
    private javax.swing.JMenuItem mnuHeThong_mniDX;
    private javax.swing.JMenuItem mnuHeThong_mniKT;
    private javax.swing.JMenu mnuTK;
    // End of variables declaration//GEN-END:variables
}
