package com.poly.model;

import com.formdev.flatlaf.intellijthemes.FlatArcIJTheme;
import com.poly.utils.XImage;

/**
 *
 * @author admin
 */
public class SanPhamJFrame extends javax.swing.JFrame {

    /**
     * Creates new form SanPhamJFrame
     */
    public SanPhamJFrame() {
        initComponents();
        this.setIconImage(XImage.getAppIcon());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlCapNhat = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtTenSP = new javax.swing.JTextField();
        btnLamMoi = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblHinh = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDiaChi = new javax.swing.JTextArea();
        btnHinh = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        cboKichThuoc = new javax.swing.JComboBox<>();
        cboLoai = new javax.swing.JComboBox<>();
        pnlDanhSach = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblSP = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("KLShop - Quản lý sản phẩm");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("QUẢN LÝ SẢN PHẨM");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 250, 41));

        jLabel3.setText("Chú ý các trường (*) là bắt buộc.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        pnlCapNhat.setBackground(new java.awt.Color(255, 255, 255));
        pnlCapNhat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("<html><p><strong style=\"color:red\">*</strong> Tên sản phẩm:</p></htm>");
        pnlCapNhat.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
        pnlCapNhat.add(txtTenSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 750, 40));

        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/Refresh.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        pnlCapNhat.add(btnLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 370, 150, 50));

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/Add.png"))); // NOI18N
        btnThem.setText("Thêm");
        pnlCapNhat.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, 130, 50));

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/Edit.png"))); // NOI18N
        btnSua.setText("Sửa");
        pnlCapNhat.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 440, 130, 50));

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/Delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        pnlCapNhat.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 440, 130, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("<html><p><strong style=\"color:red\">*</strong> Đơn giá:</p></htm>");
        pnlCapNhat.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        lblHinh.setBackground(new java.awt.Color(255, 255, 255));
        lblHinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/img/default.jpg"))); // NOI18N
        lblHinh.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 204, 204)));
        pnlCapNhat.add(lblHinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 40, 240, 240));
        pnlCapNhat.add(txtDonGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 370, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("<html><p><strong style=\"color:red\">*</strong> Loại sản phẩm:</p></htm>");
        pnlCapNhat.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("<html><p><strong style=\"color:red\">*</strong> Số lượng:</p></htm>");
        pnlCapNhat.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("<html><p><strong style=\"color:red\">*</strong> Kích thước:</p></htm>");
        pnlCapNhat.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("<html><p><strong style=\"color:red\">*</strong> Mô tả:</p></htm>");
        pnlCapNhat.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        txtDiaChi.setColumns(20);
        txtDiaChi.setLineWrap(true);
        txtDiaChi.setRows(5);
        jScrollPane2.setViewportView(txtDiaChi);

        pnlCapNhat.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 540, 190));

        btnHinh.setText("Chọn hình");
        pnlCapNhat.add(btnHinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 290, 240, -1));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99, 1));
        pnlCapNhat.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 370, 40));

        cboKichThuoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L", "M", "S", "XXL" }));
        pnlCapNhat.add(cboKichThuoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 370, 40));

        cboLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Áo thun", "Áo khoác", "Quần" }));
        pnlCapNhat.add(cboLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 370, 40));

        jTabbedPane1.addTab("CẬP NHẬT", pnlCapNhat);

        pnlDanhSach.setBackground(new java.awt.Color(255, 255, 255));
        pnlDanhSach.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlDanhSach.add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 640, -1));

        btnTimKiem.setText("Tìm");
        pnlDanhSach.add(btnTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 90, -1));

        tblSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"545454", "4545", "54545", "54", "45", "454", "4545", "455"},
                {"121", "12", "2121", "43", "4545", "4545", "545", "4545"},
                {"1212", "21", "21", "212", "2121", "12", "2112", "2112"}
            },
            new String [] {
                "Mã SP", "Tên SP", "Loại", "Giá", "Số lượng", "Mô tả", "Hình", "Size"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblSP);

        pnlDanhSach.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1010, -1));

        jTabbedPane1.addTab("DANH SÁCH", pnlDanhSach);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 1040, 590));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 760));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatArcIJTheme.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SanPhamJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHinh;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboKichThuoc;
    private javax.swing.JComboBox<String> cboLoai;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JPanel pnlCapNhat;
    private javax.swing.JPanel pnlDanhSach;
    private javax.swing.JTable tblSP;
    private javax.swing.JTextArea txtDiaChi;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
